# Generated by Django 4.2.7 on 2024-01-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_category_subscribers_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='user',
            new_name='subscriber',
        ),
    ]
